using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ScripTube.Classes.YouTube
{
    public class Subtitle
    {
        public string LanguageCode { get; }
        public string LanguageName { get; }
        public bool IsAutoGenerated { get; } // automatic-speech-recognition

        private ObservableCollection<SubtitleItem> mItems = new ObservableCollection<SubtitleItem>();
        public ObservableCollection<SubtitleItem> Items
        {
            get { return mItems; }
        }

        public Subtitle(JToken languageCode, JToken languageName, JToken asr)
        {
            LanguageCode = languageCode.ToString();
            LanguageName = languageName.ToString();
            IsAutoGenerated = (asr != null && asr.ToString() == "asr");
        }

        public void AddItem(SubtitleItem item)
        {
            mItems.Add(item);
        }

        public int GetIndexBySeconds(double currentTime)
        {
            int left = 0;
            int right = mItems.Count - 1;
            int mid = (left + right) / 2;
            while (left < right)
            {
                if (currentTime >= mItems[mid].StartSeconds && currentTime < mItems[mid].StartSeconds + mItems[mid].DurationSeconds)
                {
                    return mid;
                }
                if (currentTime < mItems[mid].StartSeconds)
                {
                    right = mid - 1;
                }
                else if (currentTime > mItems[mid].StartSeconds)
                {
                    left = mid + 1;
                }
                mid = (left + right) / 2;
            }
            return mid;
        }
    }
}
